#!/usr/bin/env bash
# smoke-image-roundtrip.sh — Stage-1 hero-image lifecycle smoke test.
#
# Proves, against the REAL qant-blog-drafts Firestore:
#   1. attach_draft_image.py writes images/hero with the contract shape
#   2. the oversize gate rejects with exit 3 and leaves the doc unchanged
#   3. copy_draft_image.py carries the hero to a second draft (source=copied:)
#   4. list_pending_rewrites.py surfaces review_targets
#   5. clear_review_state.py clears the flag trio
#   6. delete_inbox_draft.py cascades the images subcollection
#
# Uses the redbridgecyber brand + adam-burgess author (same as
# smoke-author-dual-write.sh). All test docs are deleted on exit, pass or
# fail. Exits 0 on success.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SA_KEY="${BLOG_DRAFTS_SA_KEY:-/Users/adam/Projects/qant/qant-blog-drafts.json}"

export QANT_BLOG_DRAFTS_PROJECT_ID="${QANT_BLOG_DRAFTS_PROJECT_ID:-qant-blog-drafts}"
export QANT_BLOG_DRAFTS_WRITER_KEY="${QANT_BLOG_DRAFTS_WRITER_KEY:-$SA_KEY}"

STAMP="$(date +%s | tail -c 8)"
BRAND="redbridgecyber"
TMPDIR_SMOKE="$(mktemp -d /tmp/smoke-image-XXXXXX)"
DRAFT_ID_1=""
DRAFT_ID_2=""

fail() { echo "✗ FAIL: $*" >&2; exit 1; }
pass() { echo "✓ $*"; }
info() { echo "  $*"; }

cleanup() {
  set +e
  for ID in "$DRAFT_ID_1" "$DRAFT_ID_2"; do
    [ -n "$ID" ] && python3 "$SCRIPT_DIR/delete_inbox_draft.py" \
      --brand-slug "$BRAND" --draft-id "$ID" \
      --reason "smoke-image-roundtrip cleanup" >/dev/null 2>&1
  done
  rm -rf "$TMPDIR_SMOKE"
}
trap cleanup EXIT

_submit_draft() {  # $1 = slug suffix → echoes draft_id
  local PAYLOAD="$TMPDIR_SMOKE/payload-$1.json"
  cat > "$PAYLOAD" <<EOF
{
  "title":          "IMAGE-SMOKE-${STAMP}-$1",
  "slug":           "image-smoke-${STAMP}-$1",
  "category":       "visibility",
  "target_keyword": "image roundtrip smoke",
  "body_markdown":  "# Image smoke draft $1\n\nGenerated by smoke-image-roundtrip.sh. Delete me."
}
EOF
  python3 "$SCRIPT_DIR/submit_draft_firestore.py" \
    --brand-slug "$BRAND" --author adam-burgess --payload "$PAYLOAD" \
    | python3 -c 'import json,sys; print(json.load(sys.stdin)["draft_id"])'
}

# ── 1. Seed a draft and attach a hero ──────────────────────────────────────
info "step 1: submit draft + attach_draft_image.py"
DRAFT_ID_1="$(_submit_draft a)"
info "draft 1: $DRAFT_ID_1"

printf 'RIFF....WEBPVP8 smoke-test-image-bytes' > "$TMPDIR_SMOKE/hero.webp"
ATTACH_OUT="$(python3 "$SCRIPT_DIR/attach_draft_image.py" \
  --brand-slug "$BRAND" --draft-id "$DRAFT_ID_1" \
  --image "$TMPDIR_SMOKE/hero.webp" --mime image/webp \
  --width 1200 --height 630 --source banana)"
echo "$ATTACH_OUT" | grep -q "images/hero" || fail "attach output missing image_path: $ATTACH_OUT"

SA_KEY="$SA_KEY" BRAND="$BRAND" DRAFT_ID="$DRAFT_ID_1" python3 <<'PYEOF'
import base64, os, sys
import firebase_admin
from firebase_admin import credentials, firestore

cred = credentials.Certificate(os.environ["SA_KEY"])
firebase_admin.initialize_app(cred, {"projectId": "qant-blog-drafts"})
db = firestore.client()
snap = (db.collection("brands").document(os.environ["BRAND"])
          .collection("drafts").document(os.environ["DRAFT_ID"])
          .collection("images").document("hero").get())
if not snap.exists:
    sys.exit("✗ FAIL: images/hero doc missing after attach")
d = snap.to_dict()
assert d["mime"] == "image/webp", d
assert d["width"] == 1200 and d["height"] == 630, d
assert d["state"] == "generated", d
assert d["source"] == "banana", d
assert base64.b64decode(d["data"]).startswith(b"RIFF"), "data does not round-trip"
assert d.get("createdAt") is not None, "createdAt not stamped"
print(f"  images/hero ok: {d['size_bytes']} bytes, state={d['state']}")
PYEOF
pass "hero doc written with contract shape"

# ── 2. Oversize attach → exit 3, doc unchanged ────────────────────────────
info "step 2: oversize payload rejected"
python3 -c "import sys; sys.stdout.buffer.write(b'\\xff' * 800_000)" > "$TMPDIR_SMOKE/huge.webp"
set +e
python3 "$SCRIPT_DIR/attach_draft_image.py" \
  --brand-slug "$BRAND" --draft-id "$DRAFT_ID_1" \
  --image "$TMPDIR_SMOKE/huge.webp" --mime image/webp \
  --width 1200 --height 630 --source banana 2>/dev/null
RC=$?
set -e
[ "$RC" -eq 3 ] || fail "oversize attach exited $RC, expected 3"
pass "oversize payload exits 3 (re-encode signal)"

# ── 3. Copy to a second draft ──────────────────────────────────────────────
info "step 3: copy_draft_image.py to a second draft"
DRAFT_ID_2="$(_submit_draft b)"
info "draft 2: $DRAFT_ID_2"
COPY_OUT="$(python3 "$SCRIPT_DIR/copy_draft_image.py" \
  --brand-slug "$BRAND" --from-draft-id "$DRAFT_ID_1" --to-draft-id "$DRAFT_ID_2")"
echo "$COPY_OUT" | grep -q "drafts/$DRAFT_ID_2/images/hero" || fail "copy output unexpected: $COPY_OUT"

SA_KEY="$SA_KEY" BRAND="$BRAND" SRC="$DRAFT_ID_1" DST="$DRAFT_ID_2" python3 <<'PYEOF'
import os, sys
import firebase_admin
from firebase_admin import credentials, firestore
try:
    firebase_admin.get_app()
except ValueError:
    firebase_admin.initialize_app(credentials.Certificate(os.environ["SA_KEY"]), {"projectId": "qant-blog-drafts"})
db = firestore.client()
snap = (db.collection("brands").document(os.environ["BRAND"])
          .collection("drafts").document(os.environ["DST"])
          .collection("images").document("hero").get())
if not snap.exists:
    sys.exit("✗ FAIL: copied images/hero missing on target draft")
d = snap.to_dict()
assert d["source"] == f"copied:{os.environ['SRC']}", d["source"]
assert d["state"] == "generated", d["state"]
print(f"  copied hero ok: source={d['source']}")
PYEOF
pass "hero copied with source=copied:<orig>"

# ── 4. Flag + list surfaces review_targets, then clear ────────────────────
info "step 4: review_targets through list_pending_rewrites + clear_review_state"
SA_KEY="$SA_KEY" BRAND="$BRAND" DRAFT_ID="$DRAFT_ID_1" python3 <<'PYEOF'
import os
import firebase_admin
from firebase_admin import credentials, firestore
try:
    firebase_admin.get_app()
except ValueError:
    firebase_admin.initialize_app(credentials.Certificate(os.environ["SA_KEY"]), {"projectId": "qant-blog-drafts"})
db = firestore.client()
(db.collection("brands").document(os.environ["BRAND"])
   .collection("drafts").document(os.environ["DRAFT_ID"])
   .update({"review_state": "needs_rewrite",
            "review_instructions": "smoke guidance",
            "review_targets": {"content": False, "image": True}}))
print("  flag set: image-only")
PYEOF

LIST_OUT="$(python3 "$SCRIPT_DIR/list_pending_rewrites.py" --brand "$BRAND")"
echo "$LIST_OUT" | DRAFT_ID="$DRAFT_ID_1" python3 -c '
import json, os, sys
rows = json.load(sys.stdin)
row = next((r for r in rows if r["draft_id"] == os.environ["DRAFT_ID"]), None)
assert row is not None, "flagged smoke draft not in queue"
assert row["review_targets"] == {"content": False, "image": True}, row["review_targets"]
print("  queue row carries review_targets")
'
pass "list_pending_rewrites surfaces review_targets"

python3 "$SCRIPT_DIR/clear_review_state.py" \
  --brand-slug "$BRAND" --draft-id "$DRAFT_ID_1" --reason "smoke clear" >/dev/null

SA_KEY="$SA_KEY" BRAND="$BRAND" DRAFT_ID="$DRAFT_ID_1" python3 <<'PYEOF'
import os, sys
import firebase_admin
from firebase_admin import credentials, firestore
try:
    firebase_admin.get_app()
except ValueError:
    firebase_admin.initialize_app(credentials.Certificate(os.environ["SA_KEY"]), {"projectId": "qant-blog-drafts"})
db = firestore.client()
d = (db.collection("brands").document(os.environ["BRAND"])
       .collection("drafts").document(os.environ["DRAFT_ID"]).get().to_dict())
for f in ("review_state", "review_instructions", "review_targets"):
    if f in d:
        sys.exit(f"✗ FAIL: {f} still present after clear_review_state")
print("  flag trio cleared")
PYEOF
pass "clear_review_state clears state + instructions + targets"

# ── 5. Delete both drafts; images subcollections must be gone ─────────────
info "step 5: delete_inbox_draft.py cascades images"
python3 "$SCRIPT_DIR/delete_inbox_draft.py" --brand-slug "$BRAND" --draft-id "$DRAFT_ID_1" >/dev/null
python3 "$SCRIPT_DIR/delete_inbox_draft.py" --brand-slug "$BRAND" --draft-id "$DRAFT_ID_2" >/dev/null

SA_KEY="$SA_KEY" BRAND="$BRAND" D1="$DRAFT_ID_1" D2="$DRAFT_ID_2" python3 <<'PYEOF'
import os, sys
import firebase_admin
from firebase_admin import credentials, firestore
try:
    firebase_admin.get_app()
except ValueError:
    firebase_admin.initialize_app(credentials.Certificate(os.environ["SA_KEY"]), {"projectId": "qant-blog-drafts"})
db = firestore.client()
for draft_id in (os.environ["D1"], os.environ["D2"]):
    ref = (db.collection("brands").document(os.environ["BRAND"])
             .collection("drafts").document(draft_id))
    if ref.get().exists:
        sys.exit(f"✗ FAIL: draft {draft_id} still exists")
    leftover = list(ref.collection("images").list_documents())
    if leftover:
        sys.exit(f"✗ FAIL: orphaned images docs under {draft_id}: {[d.id for d in leftover]}")
print("  both drafts and their images subcollections are gone")
PYEOF
DRAFT_ID_1=""; DRAFT_ID_2=""
pass "delete cascades images (no orphans)"

echo
echo "✓ ALL GREEN — hero image lifecycle (attach / gate / copy / targets / clear / cascade-delete) verified against qant-blog-drafts"
