#!/usr/bin/env bash
# smoke-author-dual-write.sh — Phase F-post skill round-trip smoke test.
#
# Proves the /blog skill can:
#   1. List authors from qant-blog-drafts via load_brand_context.py
#   2. Submit a draft referencing a UI-managed author via submit_draft_firestore.py
#   3. Find the draft doc in qant-blog-drafts after submission
#   4. Clean up the test draft via firebase-admin
#
# Exits 0 on success, non-zero on any failure.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SA_KEY="${BLOG_DRAFTS_SA_KEY:-/Users/adam/Projects/qant/qant-blog-drafts.json}"

export QANT_BLOG_DRAFTS_PROJECT_ID="${QANT_BLOG_DRAFTS_PROJECT_ID:-qant-blog-drafts}"
export QANT_BLOG_DRAFTS_WRITER_KEY="${QANT_BLOG_DRAFTS_WRITER_KEY:-$SA_KEY}"

STAMP="$(date +%s | tail -c 8)"
TEST_TITLE="DUAL-WRITE-SMOKE-${STAMP}"
TEST_SLUG="dual-write-smoke-${STAMP}"
PAYLOAD_FILE="/tmp/smoke-payload-${STAMP}.json"

fail() { echo "✗ FAIL: $*" >&2; exit 1; }
pass() { echo "✓ $*"; }
info() { echo "  $*"; }

# ── 1. List authors — confirm adam-burgess is in qant-blog-drafts ─────────
info "step 1: load_brand_context.py --list-authors --brand redbridgecyber"
LIST_OUT="$(python3 "$SCRIPT_DIR/load_brand_context.py" --list-authors --brand redbridgecyber)"
if echo "$LIST_OUT" | grep -q '"slug": "adam-burgess"'; then
  pass "skill can list adam-burgess from qant-blog-drafts"
else
  fail "adam-burgess not found in --list-authors output: $LIST_OUT"
fi

# ── 2. Submit a test draft via submit_draft_firestore.py ──────────────────
info "step 2: submit_draft_firestore.py --author adam-burgess"
cat > "$PAYLOAD_FILE" <<EOF
{
  "title":          "$TEST_TITLE",
  "slug":           "$TEST_SLUG",
  "category":       "visibility",
  "target_keyword": "phase f-post smoke",
  "body_markdown":  "# Dual-write smoke draft\n\nGenerated by smoke-author-dual-write.sh.\n\nDelete me."
}
EOF

SUBMIT_OUT="$(python3 "$SCRIPT_DIR/submit_draft_firestore.py" \
  --brand-slug redbridgecyber \
  --author adam-burgess \
  --payload "$PAYLOAD_FILE")"

DRAFT_ID="$(echo "$SUBMIT_OUT" | python3 -c 'import json,sys; print(json.load(sys.stdin)["draft_id"])')"
DRAFT_PATH="$(echo "$SUBMIT_OUT" | python3 -c 'import json,sys; print(json.load(sys.stdin)["draft_path"])')"
info "draft submitted: $DRAFT_PATH"
pass "skill submitted draft referencing UI-managed author"

# ── 3. Verify via firebase-admin that the draft landed ────────────────────
info "step 3: verify draft exists in qant-blog-drafts"
SA_KEY="$SA_KEY" DRAFT_ID="$DRAFT_ID" DRAFT_PATH="$DRAFT_PATH" TEST_TITLE="$TEST_TITLE" python3 <<'PYEOF'
import os, sys
import firebase_admin
from firebase_admin import credentials, firestore

cred = credentials.Certificate(os.environ["SA_KEY"])
firebase_admin.initialize_app(cred, {"projectId": "qant-blog-drafts"})
db = firestore.client()
draft_id   = os.environ["DRAFT_ID"]
test_title = os.environ["TEST_TITLE"]
ref = db.collection("brands").document("redbridgecyber").collection("drafts").document(draft_id)
snap = ref.get()
if not snap.exists:
    print(f"✗ FAIL: draft does not exist after submit", file=sys.stderr)
    sys.exit(1)
data = snap.to_dict()
if data.get("title") != test_title:
    print(f"✗ FAIL: title mismatch: {data.get('title')!r} vs {test_title!r}", file=sys.stderr)
    sys.exit(1)
if data.get("author", {}).get("slug") != "adam-burgess":
    print(f"✗ FAIL: author.slug = {data.get('author', {}).get('slug')!r}", file=sys.stderr)
    sys.exit(1)
if data.get("author", {}).get("name") != "Adam Burgess":
    print(f"✗ FAIL: author.name = {data.get('author', {}).get('name')!r}", file=sys.stderr)
    sys.exit(1)
print(f"  draft has title={data.get('title')!r}, author={data.get('author')!r}")
PYEOF
pass "draft persisted with correct title + author stamp"

# ── 4. Clean up the test draft ────────────────────────────────────────────
info "step 4: delete test draft"
SA_KEY="$SA_KEY" DRAFT_ID="$DRAFT_ID" DRAFT_PATH="$DRAFT_PATH" python3 <<'PYEOF'
import os
import firebase_admin
from firebase_admin import credentials, firestore
try:
    firebase_admin.get_app()
except ValueError:
    firebase_admin.initialize_app(credentials.Certificate(os.environ["SA_KEY"]), {"projectId": "qant-blog-drafts"})
db = firestore.client()
db.collection("brands").document("redbridgecyber").collection("drafts").document(os.environ["DRAFT_ID"]).delete()
print(f"  deleted {os.environ['DRAFT_PATH']}")
PYEOF
pass "test draft cleaned up"

rm -f "$PAYLOAD_FILE"

echo
echo "✓ ALL GREEN — skill can list authors from qant-blog-drafts AND submit drafts referencing UI-managed authors"
